[[RLIBM_32]]
arch = "aarch64"
git-tree-sha1 = "020464b8d8297d0a429f48c2e903f226cd042637"
os = "macos"

    [[RLIBM_32.download]]
    sha256 = "5b8f8a82c531fce16fb32eff52cd27a430ba7b9cb436e2da4e716be5d6366faa"
    url = "https://github.com/JuliaBinaryWrappers/RLIBM_32_jll.jl/releases/download/RLIBM_32-v0.0.1+0/RLIBM_32.v0.0.1.aarch64-apple-darwin.tar.gz"
[[RLIBM_32]]
arch = "aarch64"
git-tree-sha1 = "f756d6ef493ecb809c9794bad64e7860e3e8210d"
libc = "glibc"
os = "linux"

    [[RLIBM_32.download]]
    sha256 = "cc00287c17d6f2fb71189e0842d0e4e6e92078d11e3ecaf017f7f81ac789abf5"
    url = "https://github.com/JuliaBinaryWrappers/RLIBM_32_jll.jl/releases/download/RLIBM_32-v0.0.1+0/RLIBM_32.v0.0.1.aarch64-linux-gnu.tar.gz"
[[RLIBM_32]]
arch = "aarch64"
git-tree-sha1 = "0f59d9c9b26f016aeb690b0b6acdf5026573177d"
libc = "musl"
os = "linux"

    [[RLIBM_32.download]]
    sha256 = "c4b43beaa18798a60d08d7c45b576ee123ef9d84f710b4009ae670ec39eb1417"
    url = "https://github.com/JuliaBinaryWrappers/RLIBM_32_jll.jl/releases/download/RLIBM_32-v0.0.1+0/RLIBM_32.v0.0.1.aarch64-linux-musl.tar.gz"
[[RLIBM_32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "908358a54382acb2844568af512196c1c49072d8"
libc = "glibc"
os = "linux"

    [[RLIBM_32.download]]
    sha256 = "ce88d091a25519cf8f652dc14ca084d0c13820b8622adbf2fb3c40ed69bd9194"
    url = "https://github.com/JuliaBinaryWrappers/RLIBM_32_jll.jl/releases/download/RLIBM_32-v0.0.1+0/RLIBM_32.v0.0.1.armv6l-linux-gnueabihf.tar.gz"
[[RLIBM_32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2d84e2fb6a5ea045ab798ab6459c35c61338e233"
libc = "musl"
os = "linux"

    [[RLIBM_32.download]]
    sha256 = "62d37f77ee6b6098c901e4613bc1d10510beb37036c57ddca865aaad32b2bc93"
    url = "https://github.com/JuliaBinaryWrappers/RLIBM_32_jll.jl/releases/download/RLIBM_32-v0.0.1+0/RLIBM_32.v0.0.1.armv6l-linux-musleabihf.tar.gz"
[[RLIBM_32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "18072e55659a2b09d79101b6592eddcb5f6d8530"
libc = "glibc"
os = "linux"

    [[RLIBM_32.download]]
    sha256 = "9fc5fe254b7cc519fee4cf5ec7da1f892b9419be9b8fa2605245e9cddff88625"
    url = "https://github.com/JuliaBinaryWrappers/RLIBM_32_jll.jl/releases/download/RLIBM_32-v0.0.1+0/RLIBM_32.v0.0.1.armv7l-linux-gnueabihf.tar.gz"
[[RLIBM_32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cc1b27f66c01e878f2b240b123b2ead5f4754f3a"
libc = "musl"
os = "linux"

    [[RLIBM_32.download]]
    sha256 = "e0960285704c1d611e8835548b015665acf5bec36f17bbef2060e21110544bc2"
    url = "https://github.com/JuliaBinaryWrappers/RLIBM_32_jll.jl/releases/download/RLIBM_32-v0.0.1+0/RLIBM_32.v0.0.1.armv7l-linux-musleabihf.tar.gz"
[[RLIBM_32]]
arch = "i686"
git-tree-sha1 = "3b6543aea28a83b8a00d4626f5a6514e3674e4d6"
libc = "glibc"
os = "linux"

    [[RLIBM_32.download]]
    sha256 = "32331f48a19b48163c670b4062c2e31730dab4b6c2686fdeca0d3ad9d38707bc"
    url = "https://github.com/JuliaBinaryWrappers/RLIBM_32_jll.jl/releases/download/RLIBM_32-v0.0.1+0/RLIBM_32.v0.0.1.i686-linux-gnu.tar.gz"
[[RLIBM_32]]
arch = "i686"
git-tree-sha1 = "5c17addee211477dc92fc99a096a2992704225dc"
libc = "musl"
os = "linux"

    [[RLIBM_32.download]]
    sha256 = "8610e6aa31faf66b5f2b40117ec3ff755ad28f0a493ea851941b801e5b14b835"
    url = "https://github.com/JuliaBinaryWrappers/RLIBM_32_jll.jl/releases/download/RLIBM_32-v0.0.1+0/RLIBM_32.v0.0.1.i686-linux-musl.tar.gz"
[[RLIBM_32]]
arch = "i686"
git-tree-sha1 = "67429148a58c6bdaa7e47b3eef84d11e674f823e"
os = "windows"

    [[RLIBM_32.download]]
    sha256 = "9b8eec3a2da5a2d8a57e14372089d0ba5d01e6a9f807a4b918c3fd3408177f25"
    url = "https://github.com/JuliaBinaryWrappers/RLIBM_32_jll.jl/releases/download/RLIBM_32-v0.0.1+0/RLIBM_32.v0.0.1.i686-w64-mingw32.tar.gz"
[[RLIBM_32]]
arch = "powerpc64le"
git-tree-sha1 = "c506f3e9f91fba8c8d79885c3b08fcbbe7b09661"
libc = "glibc"
os = "linux"

    [[RLIBM_32.download]]
    sha256 = "8cfbfc9dc90f5f790591514d89b95bf5b22b5eeb323e304dccfa592401693b9d"
    url = "https://github.com/JuliaBinaryWrappers/RLIBM_32_jll.jl/releases/download/RLIBM_32-v0.0.1+0/RLIBM_32.v0.0.1.powerpc64le-linux-gnu.tar.gz"
[[RLIBM_32]]
arch = "x86_64"
git-tree-sha1 = "3fcbc6f2e8e150a5a06397891030705a6f3882a4"
os = "macos"

    [[RLIBM_32.download]]
    sha256 = "41b9361bff9b05410c0e9b5b845519cd08ec9e751e2b0d37ab174132377f7d25"
    url = "https://github.com/JuliaBinaryWrappers/RLIBM_32_jll.jl/releases/download/RLIBM_32-v0.0.1+0/RLIBM_32.v0.0.1.x86_64-apple-darwin.tar.gz"
[[RLIBM_32]]
arch = "x86_64"
git-tree-sha1 = "d8c03ebe9e3f3fb272a64f8c4ef7007b149394b4"
libc = "glibc"
os = "linux"

    [[RLIBM_32.download]]
    sha256 = "6b9f6869fcb4fb4c1c7706002fd47e8d324554f8dd01e6110fde0bd87d5da23b"
    url = "https://github.com/JuliaBinaryWrappers/RLIBM_32_jll.jl/releases/download/RLIBM_32-v0.0.1+0/RLIBM_32.v0.0.1.x86_64-linux-gnu.tar.gz"
[[RLIBM_32]]
arch = "x86_64"
git-tree-sha1 = "f94ff643a97a07630200c538cbee10fb5366feab"
libc = "musl"
os = "linux"

    [[RLIBM_32.download]]
    sha256 = "16b439dd26378832ff5f70e31ae687402fc5b87d4e9ad0e9aa381ccbcecc65d7"
    url = "https://github.com/JuliaBinaryWrappers/RLIBM_32_jll.jl/releases/download/RLIBM_32-v0.0.1+0/RLIBM_32.v0.0.1.x86_64-linux-musl.tar.gz"
[[RLIBM_32]]
arch = "x86_64"
git-tree-sha1 = "67cdd45551cdb3069f261c35813ead20bb638f48"
os = "freebsd"

    [[RLIBM_32.download]]
    sha256 = "55142a683b13addd4022bd8aedcccdbff2f4b0c9ce42e9da086afddcd06e91ae"
    url = "https://github.com/JuliaBinaryWrappers/RLIBM_32_jll.jl/releases/download/RLIBM_32-v0.0.1+0/RLIBM_32.v0.0.1.x86_64-unknown-freebsd.tar.gz"
[[RLIBM_32]]
arch = "x86_64"
git-tree-sha1 = "3f24ebef926842132ac1359c34d26f10c837fcb5"
os = "windows"

    [[RLIBM_32.download]]
    sha256 = "402f92cd7c67dc19aeed122b2a2891138888b5a3676f0e09f133706544025d35"
    url = "https://github.com/JuliaBinaryWrappers/RLIBM_32_jll.jl/releases/download/RLIBM_32-v0.0.1+0/RLIBM_32.v0.0.1.x86_64-w64-mingw32.tar.gz"
