# Autogenerated wrapper script for RLIBM_32_jll for i686-w64-mingw32
export floatMathLib

JLLWrappers.@generate_wrapper_header("RLIBM_32")
JLLWrappers.@declare_library_product(floatMathLib, "floatMathLib.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        floatMathLib,
        "bin\\floatMathLib.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
